inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
