development:
  adapter: postgresql
  encoding: unicode
  database: marvel_characters_development
  pool: 5
  username: marvel
  password: supersecret

test:
  adapter: postgresql
  encoding: unicode
  database: marvel_characters_test
  pool: 5
  username: marvel
  password: supersecret
