# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5ac57c07613f83c3e22fc4ac7395bd75d88d5400103cc370e8b7d805257da53ef69874a9a00b646a46e1c8794eb1025a73cbe2c3bcdcd8ccda4071b6d6e513

test:
  secret_key_base: 1f51e1ff1080ab5339231b2b806527e8da8da5f3c69e10444271188ed51122760d78e9487afbaaae5f17dd0cb2e074e4b5c4a1aa8e9e2401fe621b59945c7646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
